-- This Script is Part of the Prometheus Obfuscator by Levno_710
--
-- config.lua
--
-- In this Script, some Global config Variables are defined

local NAME    = "Prometheus";
local REVISION = "Alpha";
local VERSION = "v0.2";
local BY      = "levno-710";
local AUTHOR  = "levno-710";

for _, currArg in pairs(arg) do
	if currArg == "--CI" then
		local releaseName = string.gsub(string.format("%s %s %s", NAME, REVISION, VERSION), "%s", "-")
		print(releaseName)
	end
	
	if currArg == "--FullVersion" then
		print(VERSION)
	end
end

-- Config Starts here
return {
	-- Basic Information
	Name = NAME,
	NameUpper = string.upper(NAME),
	NameAndVersion = string.format("%s %s", NAME, VERSION),
	Version = VERSION;
	Revision = REVISION;
	Author = AUTHOR;
	
	-- Obfuscation Settings
	IdentPrefix = "__prometheus_"; -- The Prefix used for Identifiers generated by PROMETHEUS. NOTE: There should be no identifiers in the script to be obfuscated starting with that prefix, because that can lead to weird bugs
	
	-- Formatting Settings
	SPACE = " "; -- The Whitespace to be used by the unparser
	TAB   = "\t"; -- The Tab Whitespace to be used by the unparser for pretty printing
	
	-- Performance Settings
	DefaultMemoryLimit = 100 * 1024 * 1024; -- 100MB default memory limit
	DefaultMaxIterations = 1000; -- Default maximum iterations for loops
	
	-- Logging Settings
	DefaultLogLevel = "info"; -- Default log level (error, warn, info, debug, trace)
	
	-- File Settings
	DefaultOutputExtension = ".obfuscated.lua"; -- Default extension for output files
	ErrorFileExtension = ".error.txt"; -- Extension for error log files
	
	-- Security Settings
	MaxFileSize = 50 * 1024 * 1024; -- 50MB maximum file size to prevent memory issues
	MaxStringLength = 1000000; -- Maximum string length to prevent DoS attacks
	
	-- Validation Settings
	StrictMode = false; -- Enable strict validation mode
	AllowEmptyFiles = false; -- Whether to allow processing empty files
	
	-- Compatibility Settings
	Lua51Compatibility = true; -- Ensure Lua 5.1 compatibility
	LuaUCompatibility = true; -- Ensure Roblox LuaU compatibility
	
	-- Advanced Settings
	EnableProfiling = false; -- Enable performance profiling
	EnableStatistics = true; -- Enable statistics collection
	EnableProgressBar = true; -- Enable progress bar display
	
	-- Error Handling
	MaxErrorCount = 100; -- Maximum number of errors before aborting
	ContinueOnError = false; -- Whether to continue processing on non-critical errors
	
	-- Output Settings
	PreserveComments = false; -- Whether to preserve comments in output
	PreserveWhitespace = false; -- Whether to preserve whitespace formatting
	MinifyOutput = true; -- Whether to minify the output code
}